services:
  transcribe:
    build: ./whisper.cpp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./models_ext:/app/models_ext
    ports:
      - 8080:8080

  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ppp
      MONGO_INITDB_ROOT_PASSWORD: ${PPP_DB_PASSWORD:?}

  bot:
    build: .
    command: ppp_bot
    volumes:
      - ./config.docker.toml:/app/config.toml
    environment:
      RUST_LOG: ${PPP_BOT_LOG:-info}

  import:
    build: .
    environment:
      RUST_LOG: ${PPP_IMPORT_LOG:-info}
    command: ppp_import
    volumes:
      - ./audio:/app/audio/
      - ./transcripts:/app/transcripts
      - ./config.docker.toml:/app/config.toml

volumes:
  mongodb_data:
      

